import type { DesktopLanguage } from './desktopPreferences'

export const DESKTOP_COPY = {
    zh: {
        navConnection: '连接',
        navAgents: '编程 Agent',
        navSettings: '设置',
        navAria: '桌面导航',
        hubStart: '开启中枢',
        hubStarting: '启动中',
        hubReadyStop: '关闭中枢',
        hubStopAction: '关闭中枢',
        phoneKicker: '手机',
        phoneTitle: '手机',
        phoneReady: '显示二维码',
        phoneWaiting: '待启动',
        accessKicker: '入口',
        accessTitle: '入口',
        openEntry: '打开入口',
        copyToken: '复制访问密钥',
        accessKeyCopied: '访问密钥已复制',
        agentsRefresh: '重新检测',
        agentsRefreshing: '检测中…',
        agentsListLabel: 'Coding Agents 可用性',
        agentsHubUnavailable: '启动后检测可用性',
        agentsCheckFailed: '无法检测 Coding Agents。',
        agentDetecting: '检测中',
        agentReady: '可用',
        agentNotInstalled: '未安装',
        agentSetupRequired: '需配置',
        agentUnsupported: '不支持',
        agentUnavailable: '不可用',
        agentInstall: '安装',
        agentConfigure: '去配置',
        agentLearnMore: '查看说明',
        agentReadyAction: '已就绪',
        agentDefaultModelLabel: '默认模型',
        agentDefaultModelAuto: '自动',
        agentModelsLabel: '模型',
        agentModelsAction: '模型',
        agentModelsLoading: '模型加载中…',
        agentModelsUnavailable: '暂无模型信息',
        agentThinkingLabel: '思考强度',
        agentReasonCommandMissing: '未找到本机命令',
        agentReasonAuthMissing: '已安装，待登录或配置密钥',
        agentReasonConfigMissing: '已安装，需完成配置',
        agentReasonPlatformUnsupported: '当前平台不支持',
        agentReasonProviderUnavailable: '服务暂不可用',
        agentReasonUnknown: '检测超时或失败，请重新检测',
        agentClaudeDescription: '最贵的编程 Agent，设计审美最佳',
        agentCodexDescription: '适合复杂逻辑，量大管饱',
        agentGeminiDescription: 'Google 家的，适合大仓库理解',
        agentOpencodeDescription: '开源 Agent，轻量透明',
        agentCursorDescription: '集多模型一体，曾经的王者',
        agentPiDescription: '极简 Agent，最少的工具，最强的稳定',
        agentCopilotDescription: 'GitHub 家的',
        connectionNeedsHub: '待启动',
        settingsLanTitle: '局域网访问',
        settingsLanLocked: '中枢运行中，重启后可更改',
        settingsLanHint: '允许同 WiFi 设备连接',
        settingsAutoUpdateTitle: '自动检查',
        settingsThemeTitle: '主题',
        settingsLanguageTitle: '语言',
        settingsUpdateTitle: '版本更新',
        settingsUpdateFallback: '',
        settingsGithubTitle: 'GitHub',
        settingsGithubHint: '源代码、反馈、交流，都在这',
        settingsGithubAction: '地址',
        updateChecking: '正在检查',
        updateInstalling: '正在安装',
        updateInstall: '安装更新',
        updateCheck: '检查',
        themeSystem: '系统',
        themeLight: '浅色',
        themeDark: '深色',
        languageSystem: '系统',
        languageZh: '中文',
        languageEn: 'English',
    },
    en: {
        navConnection: 'Connect',
        navAgents: 'Coding Agents',
        navSettings: 'Settings',
        navAria: 'Desktop navigation',
        hubStart: 'Start Hub',
        hubStarting: 'Starting',
        hubReadyStop: 'Stop Hub',
        hubStopAction: 'Stop Hub',
        phoneKicker: 'Phone',
        phoneTitle: 'Phone',
        phoneReady: 'Show QR',
        phoneWaiting: 'Waiting to start',
        accessKicker: 'Access',
        accessTitle: 'Entry',
        openEntry: 'Open entry',
        copyToken: 'Copy access key',
        accessKeyCopied: 'Access key copied',
        agentsRefresh: 'Check again',
        agentsRefreshing: 'Checking…',
        agentsListLabel: 'Coding Agents availability',
        agentsHubUnavailable: 'Check availability after start',
        agentsCheckFailed: 'Could not check Coding Agents.',
        agentDetecting: 'Checking',
        agentReady: 'Ready',
        agentNotInstalled: 'Not installed',
        agentSetupRequired: 'Needs setup',
        agentUnsupported: 'Unsupported',
        agentUnavailable: 'Unavailable',
        agentInstall: 'Install',
        agentConfigure: 'Set up',
        agentLearnMore: 'Learn more',
        agentReadyAction: 'Ready',
        agentDefaultModelLabel: 'Default model',
        agentDefaultModelAuto: 'Auto',
        agentModelsLabel: 'Models',
        agentModelsAction: 'Models',
        agentModelsLoading: 'Loading models…',
        agentModelsUnavailable: 'No model info yet',
        agentThinkingLabel: 'Thinking',
        agentReasonCommandMissing: 'Local command not found',
        agentReasonAuthMissing: 'Installed, sign-in or API key needed',
        agentReasonConfigMissing: 'Installed, setup needed',
        agentReasonPlatformUnsupported: 'Unsupported on this platform',
        agentReasonProviderUnavailable: 'Provider unavailable',
        agentReasonUnknown: 'Check timed out or failed. Check again',
        agentClaudeDescription: 'Priciest coding agent, best design taste',
        agentCodexDescription: 'Great for complex logic, generous throughput',
        agentGeminiDescription: 'Google-built, good for large-repo understanding',
        agentOpencodeDescription: 'Open-source agent, light and transparent',
        agentCursorDescription: 'Multi-model bundle, once the king',
        agentPiDescription: 'Minimal agent, fewest tools, strongest stability',
        agentCopilotDescription: 'GitHub-built',
        connectionNeedsHub: 'Waiting to start',
        settingsLanTitle: 'LAN access',
        settingsLanLocked: 'Hub is running. Change after restart',
        settingsLanHint: 'Allow same Wi‑Fi devices to use the LAN address directly.',
        settingsAutoUpdateTitle: 'Auto check',
        settingsThemeTitle: 'Theme',
        settingsLanguageTitle: 'Language',
        settingsUpdateTitle: 'Updates',
        settingsUpdateFallback: '',
        settingsGithubTitle: 'GitHub',
        settingsGithubHint: 'Source, feedback, and discussion live here',
        settingsGithubAction: 'Address',
        updateChecking: 'Checking',
        updateInstalling: 'Installing',
        updateInstall: 'Install update',
        updateCheck: 'Check',
        themeSystem: 'System',
        themeLight: 'Light',
        themeDark: 'Dark',
        languageSystem: 'System',
        languageZh: '中文',
        languageEn: 'English',
    },
} as const satisfies Record<DesktopLanguage, Record<string, string>>

export type DesktopCopy = (typeof DESKTOP_COPY)[DesktopLanguage]
