import type { DesktopLanguage } from './desktopPreferences'

export const DESKTOP_COPY = {
    zh: {
        navConnection: '连接',
        navAgents: '编程 Agent',
        navSettings: '设置',
        navAria: '桌面导航',
        hubStart: '开启中枢',
        hubStarting: '启动中',
        hubReadyStop: '关闭中枢',
        hubStopAction: '关闭中枢',
        deviceTitle: '扫码',
        deviceClearInactive: '清除离线绑定',
        accessTitle: '网址',
        accessHelp: '入口说明',
        accessHelpPublic: '公网：默认使用，在各种网络环境连接更稳定',
        accessHelpLan: '局域网：手机和电脑在同一 Wi‑Fi 时使用，通常更快',
        openEntry: '打开入口',
        agentsRefresh: '重新检测',
        agentsRefreshing: '检测中…',
        agentsListLabel: 'Coding Agents 可用性',
        agentViewSwitchLabel: 'Agent 页面',
        agentStatusTab: '状态',
        agentConfigTab: '配置',
        agentConfigAgentsLabel: '可配置 Agent',
        agentConfigSystemDefault: '系统默认',
        agentConfigSave: '保存',
        agentConfigSaving: '保存中…',
        agentConfigSaved: '配置已保存',
        agentConfigRestore: '恢复',
        agentConfigRestoring: '恢复中…',
        agentConfigRestored: '配置已恢复',
        agentConfigRestoreFailed: '无法恢复 Agent 配置。',
        agentConfigOpen: '打开配置文件',
        agentConfigOpening: '打开中…',
        agentConfigOpened: '已打开配置文件',
        agentConfigOpenFailed: '无法打开配置文件。',
        agentConfigSaveHint: '保存会自动备份上一版，可随时恢复',
        agentConfigPathPending: '配置路径读取中',
        agentConfigHubUnavailable: '启动后读取配置',
        agentConfigLoadFailed: '无法读取 Agent 配置。',
        agentConfigSaveFailed: '无法保存 Agent 配置。',
        agentConfigVersionOutdatedTitle: '版本较旧，仍可保存',
        agentConfigVersionMissingTitle: 'Agent 二进制未安装，仍可保存',
        agentConfigVersionAdvisoryShort: '未验证',
        agentConfigVersionMissing: '未安装',
        agentConfigVersionVerified: '已验证',
        agentConfigRestoreLabel: '恢复上一版',
        agentConfigRestoreEmpty: '暂无备份',
        agentsHubUnavailable: '启动后检测可用性',
        agentsCheckFailed: '无法检测 Coding Agents。',
        agentDetecting: '检测中',
        agentReady: '可用',
        agentNotInstalled: '未安装',
        agentSetupRequired: '需配置',
        agentUnsupported: '不支持',
        agentUnavailable: '不可用',
        agentInstall: '安装',
        agentConfigure: '去配置',
        agentLearnMore: '查看说明',
        agentReadyAction: '已就绪',
        agentDefaultModelLabel: '默认模型',
        agentDefaultModelAuto: '自动',
        agentModelsLabel: '模型',
        agentModelsAction: '模型',
        agentModelsLoading: '模型加载中…',
        agentModelsUnavailable: '暂无模型信息',
        agentThinkingLabel: '思考强度',
        agentReasonCommandMissing: '未找到本机命令',
        agentReasonAuthMissing: '已安装，待登录或配置密钥',
        agentReasonConfigMissing: '已安装，需完成配置',
        agentReasonPlatformUnsupported: '当前平台不支持',
        agentReasonProviderUnavailable: '服务暂不可用',
        agentReasonUnknown: '检测超时或失败，请重新检测',
        agentClaudeDescription: '最贵的编程 Agent，设计审美最佳',
        agentCodexDescription: '适合复杂逻辑，量大管饱',
        agentGeminiDescription: 'Google 家的，适合大仓库理解',
        agentOpencodeDescription: '开源 Agent，轻量透明',
        agentCursorDescription: '集多模型一体，曾经的王者',
        agentPiDescription: '极简 Agent，最少的工具，最强的稳定',
        agentCopilotDescription: 'GitHub 家的',
        connectionNeedsHub: '待启动',
        publicEntryLabel: '公网',
        publicAccessTitle: '公网访问',
        publicAccessOnHint: '不在同一 Wi‑Fi 也能扫码连接；同 Wi‑Fi 仍走局域网',
        publicAccessOffHint: '只允许同 Wi‑Fi 设备连接，外网无法新配对',
        publicAccessStateOn: '已开启',
        publicAccessStateOff: '已关闭',
        publicAccessStateBusy: '切换中',
        settingsAutoUpdateTitle: '自动检查',
        settingsThemeTitle: '主题',
        settingsLanguageTitle: '语言',
        settingsUpdateTitle: '版本更新',
        settingsUpdateFallback: '',
        settingsGithubTitle: 'GitHub',
        settingsGithubHint: '源代码、反馈、交流，都在这',
        settingsGithubAction: '地址',
        updateChecking: '正在检查',
        updateInstalling: '正在安装',
        updateInstall: '安装更新',
        updateCheck: '检查',
        themeSystem: '系统',
        themeLight: '浅色',
        themeDark: '深色',
        languageSystem: '系统',
        languageZh: '中文',
        languageEn: 'English',
    },
    en: {
        navConnection: 'Connect',
        navAgents: 'Coding Agents',
        navSettings: 'Settings',
        navAria: 'Desktop navigation',
        hubStart: 'Start Hub',
        hubStarting: 'Starting',
        hubReadyStop: 'Stop Hub',
        hubStopAction: 'Stop Hub',
        deviceTitle: 'Scan',
        deviceClearInactive: 'Clear offline pairings',
        accessTitle: 'URL',
        accessHelp: 'Entry help',
        accessHelpPublic: 'Public: used by default, more stable across different network conditions.',
        accessHelpLan: 'LAN: use it when your device and computer are on the same Wi‑Fi. It is usually faster.',
        openEntry: 'Open entry',
        agentsRefresh: 'Check again',
        agentsRefreshing: 'Checking…',
        agentsListLabel: 'Coding Agents availability',
        agentViewSwitchLabel: 'Agent page',
        agentStatusTab: 'Status',
        agentConfigTab: 'Config',
        agentConfigAgentsLabel: 'Configurable agents',
        agentConfigSystemDefault: 'System default',
        agentConfigSave: 'Save',
        agentConfigSaving: 'Saving…',
        agentConfigSaved: 'Config saved',
        agentConfigRestore: 'Restore',
        agentConfigRestoring: 'Restoring…',
        agentConfigRestored: 'Config restored',
        agentConfigRestoreFailed: 'Could not restore agent config.',
        agentConfigOpen: 'Open config file',
        agentConfigOpening: 'Opening…',
        agentConfigOpened: 'Config file opened',
        agentConfigOpenFailed: 'Could not open config file.',
        agentConfigSaveHint: 'Saving snapshots the previous file; restore anytime.',
        agentConfigPathPending: 'Loading config path',
        agentConfigHubUnavailable: 'Read config after start',
        agentConfigLoadFailed: 'Could not read agent config.',
        agentConfigSaveFailed: 'Could not save agent config.',
        agentConfigVersionOutdatedTitle: 'Older agent binary — saving still works',
        agentConfigVersionMissingTitle: 'Agent binary not installed — saving still works',
        agentConfigVersionAdvisoryShort: 'Unverified',
        agentConfigVersionMissing: 'Not installed',
        agentConfigVersionVerified: 'Verified',
        agentConfigRestoreLabel: 'Restore previous',
        agentConfigRestoreEmpty: 'No backup yet',
        agentsHubUnavailable: 'Check availability after start',
        agentsCheckFailed: 'Could not check Coding Agents.',
        agentDetecting: 'Checking',
        agentReady: 'Ready',
        agentNotInstalled: 'Not installed',
        agentSetupRequired: 'Needs setup',
        agentUnsupported: 'Unsupported',
        agentUnavailable: 'Unavailable',
        agentInstall: 'Install',
        agentConfigure: 'Set up',
        agentLearnMore: 'Learn more',
        agentReadyAction: 'Ready',
        agentDefaultModelLabel: 'Default model',
        agentDefaultModelAuto: 'Auto',
        agentModelsLabel: 'Models',
        agentModelsAction: 'Models',
        agentModelsLoading: 'Loading models…',
        agentModelsUnavailable: 'No model info yet',
        agentThinkingLabel: 'Thinking',
        agentReasonCommandMissing: 'Local command not found',
        agentReasonAuthMissing: 'Installed, sign-in or API key needed',
        agentReasonConfigMissing: 'Installed, setup needed',
        agentReasonPlatformUnsupported: 'Unsupported on this platform',
        agentReasonProviderUnavailable: 'Provider unavailable',
        agentReasonUnknown: 'Check timed out or failed. Check again',
        agentClaudeDescription: 'Priciest coding agent, best design taste',
        agentCodexDescription: 'Great for complex logic, generous throughput',
        agentGeminiDescription: 'Google-built, good for large-repo understanding',
        agentOpencodeDescription: 'Open-source agent, light and transparent',
        agentCursorDescription: 'Multi-model bundle, once the king',
        agentPiDescription: 'Minimal agent, fewest tools, strongest stability',
        agentCopilotDescription: 'GitHub-built',
        connectionNeedsHub: 'Waiting to start',
        publicEntryLabel: 'Public',
        publicAccessTitle: 'Public access',
        publicAccessOnHint: 'Scan from outside the same Wi‑Fi; LAN still uses the local address.',
        publicAccessOffHint: 'Only same Wi‑Fi devices can connect. New public pairing is paused.',
        publicAccessStateOn: 'On',
        publicAccessStateOff: 'Off',
        publicAccessStateBusy: 'Switching',
        settingsAutoUpdateTitle: 'Auto check',
        settingsThemeTitle: 'Theme',
        settingsLanguageTitle: 'Language',
        settingsUpdateTitle: 'Updates',
        settingsUpdateFallback: '',
        settingsGithubTitle: 'GitHub',
        settingsGithubHint: 'Source, feedback, and discussion live here',
        settingsGithubAction: 'Address',
        updateChecking: 'Checking',
        updateInstalling: 'Installing',
        updateInstall: 'Install update',
        updateCheck: 'Check',
        themeSystem: 'System',
        themeLight: 'Light',
        themeDark: 'Dark',
        languageSystem: 'System',
        languageZh: '中文',
        languageEn: 'English',
    },
} as const satisfies Record<DesktopLanguage, Record<string, string>>

export type DesktopCopy = (typeof DESKTOP_COPY)[DesktopLanguage]
