import type { DesktopLanguage } from './desktopPreferences'

export const DESKTOP_COPY = {
    zh: {
        navConnection: '连接',
        navAgents: '编程 Agent',
        navSettings: '设置',
        navAria: '桌面导航',
        hubStart: '开启中枢',
        hubStarting: '启动中',
        hubReadyStop: '关闭中枢',
        hubStopAction: '关闭中枢',
        phoneKicker: '手机',
        phoneTitle: '连接手机',
        phoneReady: '显示二维码',
        phoneWaiting: '先开启中枢',
        accessKicker: '入口',
        accessTitle: '入口地址',
        openEntry: '打开入口地址',
        copyToken: '复制访问密钥',
        accessKeyCopied: '访问密钥已复制',
        agentsTitle: '编程 Agent',
        agentsRefresh: '重新检测',
        agentsRefreshing: '检测中…',
        agentsListLabel: 'Coding Agents 可用性',
        agentWaiting: '等待检测',
        agentReady: '可用',
        agentNotInstalled: '未安装',
        agentSetupRequired: '需配置',
        agentUnsupported: '不支持',
        agentUnavailable: '不可用',
        agentInstall: '去安装',
        agentConfigure: '去配置',
        agentLearnMore: '查看说明',
        agentReadyAction: '已就绪',
        connectionNeedsHub: '开启中枢后显示连接入口',
        settingsLanTitle: '局域网访问',
        settingsLanLocked: '中枢运行中，重启后可更改。',
        settingsLanHint: '允许同一 Wi‑Fi 下设备直接局域网地址',
        settingsAutoUpdateTitle: '自动检查更新',
        settingsThemeTitle: '明暗主题',
        settingsLanguageTitle: '语言',
        settingsUpdateTitle: '版本更新',
        settingsUpdateFallback: '手动检查 GitHub Release 更新。',
        updateChecking: '正在检查',
        updateInstalling: '正在安装',
        updateInstall: '安装更新',
        updateCheck: '检查更新',
        themeSystem: '系统',
        themeLight: '浅色',
        themeDark: '深色',
        languageSystem: '系统',
        languageZh: '中文',
        languageEn: 'English',
    },
    en: {
        navConnection: 'Connect',
        navAgents: 'Coding Agents',
        navSettings: 'Settings',
        navAria: 'Desktop navigation',
        hubStart: 'Start Hub',
        hubStarting: 'Starting',
        hubReadyStop: 'Stop Hub',
        hubStopAction: 'Stop Hub',
        phoneKicker: 'Phone',
        phoneTitle: 'Pair phone',
        phoneReady: 'Show QR',
        phoneWaiting: 'Start Hub first',
        accessKicker: 'Access',
        accessTitle: 'Entry URL',
        openEntry: 'Open entry URL',
        copyToken: 'Copy access key',
        accessKeyCopied: 'Access key copied',
        agentsTitle: 'Coding Agents',
        agentsRefresh: 'Check again',
        agentsRefreshing: 'Checking…',
        agentsListLabel: 'Coding Agents availability',
        agentWaiting: 'Waiting',
        agentReady: 'Ready',
        agentNotInstalled: 'Not installed',
        agentSetupRequired: 'Needs setup',
        agentUnsupported: 'Unsupported',
        agentUnavailable: 'Unavailable',
        agentInstall: 'Install',
        agentConfigure: 'Set up',
        agentLearnMore: 'Learn more',
        agentReadyAction: 'Ready',
        connectionNeedsHub: 'Start Hub to show connection options',
        settingsLanTitle: 'LAN access',
        settingsLanLocked: 'Hub is running. Change after restart.',
        settingsLanHint: 'Allow same Wi‑Fi devices to use the LAN address directly.',
        settingsAutoUpdateTitle: 'Auto update checks',
        settingsThemeTitle: 'Theme',
        settingsLanguageTitle: 'Language',
        settingsUpdateTitle: 'Updates',
        settingsUpdateFallback: 'Check GitHub Releases manually.',
        updateChecking: 'Checking',
        updateInstalling: 'Installing',
        updateInstall: 'Install update',
        updateCheck: 'Check updates',
        themeSystem: 'System',
        themeLight: 'Light',
        themeDark: 'Dark',
        languageSystem: 'System',
        languageZh: '中文',
        languageEn: 'English',
    },
} as const satisfies Record<DesktopLanguage, Record<string, string>>

export type DesktopCopy = (typeof DESKTOP_COPY)[DesktopLanguage]
