import { PAIRING_MOBILE_DISCONNECT_GRACE_MS } from '@viby/protocol/pairing'

export const PAIRING_PHONE_PAUSED_MESSAGE = '手机在后台，回来后会自动接回。'
export const PAIRING_TRANSPORT_RECOVERY_GRACE_MS = PAIRING_MOBILE_DISCONNECT_GRACE_MS
