import { describe, expect, it } from 'bun:test'

function toPermission(command: string): string {
    return `allow-${command.replaceAll('_', '-')}`
}

async function readText(path: string): Promise<string> {
    return await Bun.file(path).text()
}

function collectMatches(pattern: RegExp, text: string): string[] {
    return [...text.matchAll(pattern)].map((match) => match[1])
}

describe('tauri command policy', () => {
    it('keeps desktop API commands registered and allowed by Tauri ACL', async () => {
        const desktopApi = await readText('src/lib/desktopApi.ts')
        const capability = await Bun.file('src-tauri/capabilities/default.json').json()
        const lib = await readText('src-tauri/src/lib.rs')
        const build = await readText('src-tauri/build.rs')

        const apiCommands = collectMatches(/invokeDesktopCommand(?:<[^>]+>)?\('([^']+)'/g, desktopApi)
        const registeredCommands = collectMatches(/commands::([a-z_]+)/g, lib)
        const commands = Array.from(new Set([...apiCommands, ...registeredCommands]))

        expect(apiCommands.length).toBeGreaterThan(0)
        expect(new Set(registeredCommands)).toEqual(new Set(commands))
        for (const command of commands) {
            const permissionName = toPermission(command)
            const permission = await readText(`src-tauri/permissions/autogenerated/${command}.toml`)
            expect(capability.permissions).toContain(permissionName)
            expect(permission).toContain(`identifier = "${permissionName}"`)
            expect(permission).toContain(`commands.allow = ["${command}"]`)
            expect(lib).toContain(`commands::${command}`)
            expect(build).toContain(`"${command}"`)
        }

        expect(commands).not.toContain('get_pairing_session')
        expect(commands).not.toContain('clear_pairing_session')
    })
})
