import { describe, expect, it } from 'bun:test'

const COMMAND = 'set_public_access_enabled'
const PERMISSION = 'allow-set-public-access-enabled'

describe('tauri command policy', () => {
    it('allows the public access settings command in the main-window capability', async () => {
        const capability = await Bun.file('src-tauri/capabilities/default.json').json()
        expect(capability.permissions).toContain(PERMISSION)
    })

    it('defines the matching ACL permission for the public access settings command', async () => {
        const permission = await Bun.file('src-tauri/permissions/autogenerated/set_public_access_enabled.toml').text()
        expect(permission).toContain(`identifier = "${PERMISSION}"`)
        expect(permission).toContain(`commands.allow = ["${COMMAND}"]`)
    })

    it('registers the command in the Tauri invoke handler', async () => {
        const lib = await Bun.file('src-tauri/src/lib.rs').text()
        expect(lib).toContain(`commands::${COMMAND}`)
    })
})
