import type { AgentConfigFieldDefinition } from './agentConfig'
import { approvalOptions, field, reasoningOptions } from './agentConfigCatalogSupport'

export const CODEX_CLAUDE_AGENT_CONFIG_FIELDS: readonly AgentConfigFieldDefinition[] = [
    field({
        id: 'codex.model',
        driver: 'codex',
        group: 'model',
        path: 'model',
        control: 'select',
        label: ['Default model', '默认模型'],
        help: ['Model Codex starts with when no session override is set', '没有会话覆盖时 Codex 默认使用的模型'],
        options: [
            ['gpt-5.5', 'GPT-5.5', 'GPT-5.5'],
            ['gpt-5.4', 'GPT-5.4', 'GPT-5.4'],
            ['gpt-5.4-mini', 'GPT-5.4 Mini', 'GPT-5.4 Mini'],
            ['gpt-5.3-codex', 'GPT-5.3 Codex', 'GPT-5.3 Codex'],
            ['gpt-5.2', 'GPT-5.2', 'GPT-5.2'],
        ],
    }),
    field({
        id: 'codex.model_reasoning_effort',
        driver: 'codex',
        group: 'model',
        path: 'model_reasoning_effort',
        control: 'select',
        label: ['Reasoning effort', '思考强度'],
        help: ['Higher effort spends more compute on hard tasks', '越高越适合复杂任务，也会更慢'],
        options: reasoningOptions,
    }),
    field({
        id: 'codex.approval_policy',
        driver: 'codex',
        group: 'safety',
        path: 'approval_policy',
        control: 'select',
        label: ['Approval policy', '审批策略'],
        help: ['Controls when Codex asks before running commands', '控制 Codex 运行命令前什么时候询问'],
        options: approvalOptions,
    }),
    field({
        id: 'codex.sandbox_mode',
        driver: 'codex',
        group: 'safety',
        path: 'sandbox_mode',
        control: 'select',
        label: ['Sandbox', '沙箱'],
        help: ['Limits command file-system access', '限制命令能读写的文件范围'],
        options: [
            ['read-only', 'Read only', '只读'],
            ['workspace-write', 'Workspace write', '可写工作区'],
            ['danger-full-access', 'Full access', '完全访问'],
        ],
    }),
    field({
        id: 'codex.sandbox_workspace_write.network_access',
        driver: 'codex',
        group: 'safety',
        path: 'sandbox_workspace_write.network_access',
        control: 'toggle',
        label: ['Network in workspace sandbox', '工作区沙箱允许联网'],
        help: ['Only applies when sandbox is workspace-write', '只在可写工作区沙箱下生效'],
        defaultValue: false,
    }),
    field({
        id: 'codex.history.persistence',
        driver: 'codex',
        group: 'memory',
        path: 'history.persistence',
        control: 'select',
        label: ['History', '历史记录'],
        help: ['Choose whether Codex saves local conversation history', '选择 Codex 是否保存本机会话历史'],
        options: [
            ['save-all', 'Save history', '保存历史'],
            ['none', 'Do not save', '不保存'],
        ],
    }),
    field({
        id: 'claude.model',
        driver: 'claude',
        group: 'model',
        path: 'model',
        control: 'select',
        label: ['Default model', '默认模型'],
        help: [
            'Initial Claude Code model. Users can still switch in a session',
            'Claude Code 启动模型，会话中仍可切换',
        ],
        options: [
            ['default', 'Default', '默认'],
            ['sonnet', 'Sonnet', 'Sonnet'],
            ['opus', 'Opus', 'Opus'],
            ['haiku', 'Haiku', 'Haiku'],
            ['opusplan', 'Opus plan', 'Opus 规划'],
        ],
    }),
    field({
        id: 'claude.effortLevel',
        driver: 'claude',
        group: 'model',
        path: 'effortLevel',
        control: 'select',
        label: ['Effort level', '默认思考强度'],
        help: ['Default thinking effort. Max only works per session', '默认思考强度，Max 仅支持会话内启用'],
        options: reasoningOptions.filter((item) => item[0] !== 'none' && item[0] !== 'minimal'),
    }),
    field({
        id: 'claude.permissions.defaultMode',
        driver: 'claude',
        group: 'safety',
        path: 'permissions.defaultMode',
        control: 'select',
        label: ['Permission mode', '权限模式'],
        help: ['Default tool approval mode when Claude Code opens', 'Claude Code 打开时默认工具审批模式'],
        options: [
            ['default', 'Default', '默认'],
            ['acceptEdits', 'Accept edits', '自动接受编辑'],
            ['plan', 'Plan', '规划'],
            ['auto', 'Auto', '自动'],
            ['dontAsk', 'Do not ask', '不询问'],
            ['bypassPermissions', 'Bypass permissions', '跳过权限'],
        ],
    }),
    field({
        id: 'claude.permissions.disableBypassPermissionsMode',
        driver: 'claude',
        group: 'safety',
        path: 'permissions.disableBypassPermissionsMode',
        control: 'toggle',
        label: ['Block bypass mode', '禁用跳过权限'],
        help: ['Prevents dangerous bypass permissions mode from being activated', '阻止启用危险的跳过权限模式'],
    }),
    field({
        id: 'claude.permissions.denySensitiveFiles',
        driver: 'claude',
        group: 'safety',
        path: 'permissions.deny',
        control: 'toggle',
        label: ['Deny common secret files', '拒绝常见密钥文件'],
        help: ['Adds deny rules for .env and secrets folders', '加入 .env 和 secrets 目录的拒绝规则'],
    }),
    field({
        id: 'claude.sandbox.enabled',
        driver: 'claude',
        group: 'safety',
        path: 'sandbox.enabled',
        control: 'toggle',
        label: ['Bash sandbox', 'Bash 沙箱'],
        help: [
            'Isolates shell commands from broad filesystem and network access',
            '隔离 shell 命令，减少文件和网络越界',
        ],
    }),
    field({
        id: 'claude.includeCoAuthoredBy',
        driver: 'claude',
        group: 'git',
        path: 'includeCoAuthoredBy',
        control: 'toggle',
        label: ['Commit attribution', '提交署名'],
        help: ['Adds Claude co-author trailers to generated commits', '为 Claude 生成的提交加入共同作者署名'],
        defaultValue: true,
    }),
]
