import type { AgentConfigFieldDefinition } from './agentConfig'
import { field } from './agentConfigCatalogSupport'

export const GEMINI_PI_COPILOT_LATEST_CONFIG_FIELDS: readonly AgentConfigFieldDefinition[] = [
    field({
        id: 'gemini.general.vimMode',
        driver: 'gemini',
        group: 'ui',
        path: 'general.vimMode',
        control: 'toggle',
        label: ['Vim mode', 'Vim 模式'],
        help: ['Enables Vim keybindings in Gemini CLI', '在 Gemini CLI 中启用 Vim 按键'],
        defaultValue: false,
    }),
    field({
        id: 'gemini.output.format',
        driver: 'gemini',
        group: 'runtime',
        path: 'output.format',
        control: 'select',
        label: ['Output format', '输出格式'],
        help: ['Terminal output format for Gemini CLI', 'Gemini CLI 的终端输出格式'],
        defaultValue: 'text',
        options: [
            ['text', 'Text', '文本'],
            ['json', 'JSON', 'JSON'],
        ],
    }),
    field({
        id: 'gemini.ui.inlineThinkingMode',
        driver: 'gemini',
        group: 'ui',
        path: 'ui.inlineThinkingMode',
        control: 'select',
        label: ['Inline thinking', '内联思考'],
        help: ['Controls whether Gemini shows model thinking inline', '控制 Gemini 是否内联显示模型思考'],
        defaultValue: 'off',
        options: [
            ['off', 'Off', '关闭'],
            ['full', 'Full', '完整'],
        ],
    }),
    field({
        id: 'gemini.ui.footer.hideModelInfo',
        driver: 'gemini',
        group: 'ui',
        path: 'ui.footer.hideModelInfo',
        control: 'toggle',
        label: ['Hide model footer', '隐藏模型状态'],
        help: ['Hides model and context usage from the footer', '在底部隐藏模型和上下文用量'],
        defaultValue: false,
    }),
    field({
        id: 'gemini.ui.errorVerbosity',
        driver: 'gemini',
        group: 'ui',
        path: 'ui.errorVerbosity',
        control: 'select',
        label: ['Error detail', '错误细节'],
        help: ['Low hides recoverable details; full shows them', 'Low 隐藏可恢复错误细节，full 显示完整信息'],
        defaultValue: 'low',
        options: [
            ['low', 'Low', '低'],
            ['full', 'Full', '完整'],
        ],
    }),
    field({
        id: 'gemini.ide.enabled',
        driver: 'gemini',
        group: 'runtime',
        path: 'ide.enabled',
        control: 'toggle',
        label: ['IDE mode', 'IDE 模式'],
        help: ['Enables Gemini CLI IDE integration mode', '启用 Gemini CLI 的 IDE 集成模式'],
        defaultValue: false,
    }),
    field({
        id: 'gemini.billing.overageStrategy',
        driver: 'gemini',
        group: 'runtime',
        path: 'billing.overageStrategy',
        control: 'select',
        label: ['Overage strategy', '额度耗尽策略'],
        help: ['Chooses how Gemini handles quota exhaustion', '选择 Gemini 在额度耗尽时如何处理'],
        defaultValue: 'ask',
        options: [
            ['ask', 'Ask', '询问'],
            ['always', 'Always use credits', '总是使用点数'],
            ['never', 'Never', '从不'],
        ],
    }),
    field({
        id: 'gemini.model.maxSessionTurns',
        driver: 'gemini',
        group: 'model',
        path: 'model.maxSessionTurns',
        control: 'number',
        label: ['Max session turns', '最大会话轮数'],
        help: ['Maximum turns retained in a session; -1 means unlimited', '会话保留的最大轮数；-1 表示不限'],
        defaultValue: -1,
    }),
    field({
        id: 'gemini.model.compressionThreshold',
        driver: 'gemini',
        group: 'memory',
        path: 'model.compressionThreshold',
        control: 'number',
        label: ['Compression threshold', '压缩阈值'],
        help: ['Context usage fraction that triggers compression', '触发上下文压缩的用量比例'],
        defaultValue: 0.5,
    }),
    field({
        id: 'gemini.context.fileFiltering.enableFuzzySearch',
        driver: 'gemini',
        group: 'tools',
        path: 'context.fileFiltering.enableFuzzySearch',
        control: 'toggle',
        label: ['Fuzzy file search', '模糊文件搜索'],
        help: ['Enables fuzzy matching for file search', '为文件搜索启用模糊匹配'],
        defaultValue: true,
    }),
    field({
        id: 'gemini.tools.sandboxAllowedPaths',
        driver: 'gemini',
        group: 'safety',
        path: 'tools.sandboxAllowedPaths',
        control: 'list',
        label: ['Sandbox allowed paths', '沙箱允许路径'],
        help: ['Extra paths Gemini sandbox tools may access', 'Gemini 沙箱工具可访问的额外路径'],
    }),
    field({
        id: 'gemini.tools.truncateToolOutputThreshold',
        driver: 'gemini',
        group: 'tools',
        path: 'tools.truncateToolOutputThreshold',
        control: 'number',
        label: ['Tool output cap', '工具输出上限'],
        help: ['Maximum characters before large tool output is truncated', '工具输出超过此字符数后截断'],
        defaultValue: 40000,
    }),
    field({
        id: 'gemini.security.toolSandboxing',
        driver: 'gemini',
        group: 'safety',
        path: 'security.toolSandboxing',
        control: 'toggle',
        label: ['Tool sandboxing', '工具沙箱'],
        help: ['Isolates individual tools instead of the whole CLI', '隔离单个工具而不是整个 CLI'],
        defaultValue: false,
    }),
    field({
        id: 'gemini.advanced.ignoreLocalEnv',
        driver: 'gemini',
        group: 'privacy',
        path: 'advanced.ignoreLocalEnv',
        control: 'toggle',
        label: ['Ignore local .env', '忽略本地 .env'],
        help: ['Prevents Gemini from loading generic .env files', '阻止 Gemini 加载通用 .env 文件'],
        defaultValue: false,
    }),
]
