import type { AgentConfigFieldDefinition } from './agentConfig'
import { field } from './agentConfigCatalogSupport'

export const PI_COPILOT_LATEST_CONFIG_FIELDS: readonly AgentConfigFieldDefinition[] = [
    field({
        id: 'pi.compaction.enabled',
        driver: 'pi',
        group: 'memory',
        path: 'compaction.enabled',
        control: 'toggle',
        label: ['Auto compaction', '自动压缩'],
        help: ['Enables Pi context compaction.', '启用 Pi 上下文压缩。'],
        defaultValue: true,
    }),
    field({
        id: 'pi.compaction.reserveTokens',
        driver: 'pi',
        group: 'memory',
        path: 'compaction.reserveTokens',
        control: 'number',
        label: ['Reserve tokens', '保留输出 Token'],
        help: ['Tokens reserved for the next LLM response.', '为下一次模型回复预留的 Token。'],
        defaultValue: 16384,
    }),
    field({
        id: 'pi.retry.enabled',
        driver: 'pi',
        group: 'runtime',
        path: 'retry.enabled',
        control: 'toggle',
        label: ['Agent retry', 'Agent 重试'],
        help: ['Retries transient agent-level failures.', '对临时 Agent 层失败自动重试。'],
        defaultValue: true,
    }),
    field({
        id: 'pi.retry.provider.maxRetryDelayMs',
        driver: 'pi',
        group: 'runtime',
        path: 'retry.provider.maxRetryDelayMs',
        control: 'number',
        label: ['Max retry delay', '最大重试延迟'],
        help: ['Provider retry delays above this fail immediately.', '供应商要求的重试延迟超过此值时立即失败。'],
        defaultValue: 60000,
    }),
    field({
        id: 'pi.transport',
        driver: 'pi',
        group: 'runtime',
        path: 'transport',
        control: 'select',
        label: ['Transport', '传输'],
        help: ['Preferred provider transport when multiple are supported.', '供应商支持多种传输时的优先选择。'],
        defaultValue: 'sse',
        options: [
            ['sse', 'SSE', 'SSE'],
            ['websocket', 'WebSocket', 'WebSocket'],
            ['auto', 'Auto', '自动'],
        ],
    }),
    field({
        id: 'pi.terminal.showImages',
        driver: 'pi',
        group: 'ui',
        path: 'terminal.showImages',
        control: 'toggle',
        label: ['Show images', '显示图片'],
        help: ['Shows inline images when the terminal supports them.', '终端支持时显示内联图片。'],
        defaultValue: true,
    }),
    field({
        id: 'pi.images.blockImages',
        driver: 'pi',
        group: 'privacy',
        path: 'images.blockImages',
        control: 'toggle',
        label: ['Block images', '阻止图片'],
        help: ['Blocks images from being sent to the model.', '阻止图片发送给模型。'],
        defaultValue: false,
    }),
    field({
        id: 'pi.shellPath',
        driver: 'pi',
        group: 'tools',
        path: 'shellPath',
        control: 'text',
        label: ['Shell path', 'Shell 路径'],
        help: ['Custom shell executable path.', '自定义 Shell 可执行文件路径。'],
    }),
    field({
        id: 'pi.npmCommand',
        driver: 'pi',
        group: 'tools',
        path: 'npmCommand',
        control: 'list',
        label: ['NPM command', 'NPM 命令'],
        help: ['Command argv used for npm operations, one item per line.', 'npm 操作使用的命令参数，每行一个。'],
    }),
    field({
        id: 'pi.sessionDir',
        driver: 'pi',
        group: 'memory',
        path: 'sessionDir',
        control: 'text',
        label: ['Session directory', '会话目录'],
        help: ['Directory where Pi stores session files.', 'Pi 保存会话文件的目录。'],
    }),
    field({
        id: 'copilot.deniedUrls',
        driver: 'copilot',
        group: 'safety',
        path: 'deniedUrls',
        control: 'list',
        label: ['Denied URLs', '拒绝网址'],
        help: ['URLs or domains Copilot CLI should always deny.', 'Copilot CLI 总是拒绝的网址或域名。'],
    }),
    field({
        id: 'copilot.autoUpdatesChannel',
        driver: 'copilot',
        group: 'runtime',
        path: 'autoUpdatesChannel',
        control: 'select',
        label: ['Update channel', '更新通道'],
        help: ['Chooses stable or prerelease Copilot CLI updates.', '选择稳定版或预发布 Copilot CLI 更新。'],
        defaultValue: 'stable',
        options: [
            ['stable', 'Stable', '稳定'],
            ['prerelease', 'Prerelease', '预发布'],
        ],
    }),
    field({
        id: 'copilot.banner',
        driver: 'copilot',
        group: 'ui',
        path: 'banner',
        control: 'select',
        label: ['Banner', '横幅'],
        help: ['Controls animated banner display frequency.', '控制动态横幅显示频率。'],
        defaultValue: 'once',
        options: [
            ['always', 'Always', '总是'],
            ['once', 'Once', '一次'],
            ['never', 'Never', '从不'],
        ],
    }),
    field({
        id: 'copilot.colorMode',
        driver: 'copilot',
        group: 'ui',
        path: 'colorMode',
        control: 'select',
        label: ['Color mode', '颜色模式'],
        help: ['Adjusts terminal contrast and color accessibility.', '调整终端对比度与颜色可访问性。'],
        defaultValue: 'default',
        options: [
            ['default', 'Default', '默认'],
            ['dim', 'Dim', '柔和'],
            ['high-contrast', 'High contrast', '高对比'],
            ['colorblind', 'Colorblind', '色盲友好'],
        ],
    }),
    field({
        id: 'copilot.disabledMcpServers',
        driver: 'copilot',
        group: 'tools',
        path: 'disabledMcpServers',
        control: 'list',
        label: ['Disabled MCP servers', '禁用 MCP 服务'],
        help: ['Configured MCP servers that should not start.', '已配置但不应启动的 MCP 服务。'],
    }),
    field({
        id: 'copilot.enabledMcpServers',
        driver: 'copilot',
        group: 'tools',
        path: 'enabledMcpServers',
        control: 'list',
        label: ['Enabled MCP servers', '启用 MCP 服务'],
        help: ['Built-in MCP servers to enable.', '要启用的内置 MCP 服务。'],
    }),
    field({
        id: 'copilot.ide.autoConnect',
        driver: 'copilot',
        group: 'runtime',
        path: 'ide.autoConnect',
        control: 'toggle',
        label: ['IDE auto-connect', '自动连接 IDE'],
        help: ['Automatically connects to an IDE workspace on startup.', '启动时自动连接 IDE 工作区。'],
        defaultValue: true,
    }),
    field({
        id: 'copilot.ide.openDiffOnEdit',
        driver: 'copilot',
        group: 'ui',
        path: 'ide.openDiffOnEdit',
        control: 'toggle',
        label: ['Open edit diffs', '打开编辑 Diff'],
        help: ['Opens file edit diffs in the connected IDE.', '在已连接 IDE 中打开文件编辑 Diff。'],
        defaultValue: true,
    }),
    field({
        id: 'copilot.logLevel',
        driver: 'copilot',
        group: 'runtime',
        path: 'logLevel',
        control: 'select',
        label: ['Log level', '日志级别'],
        help: ['Logging verbosity for Copilot CLI.', 'Copilot CLI 日志详细程度。'],
        defaultValue: 'default',
        options: [
            ['default', 'Default', '默认'],
            ['error', 'Error', '错误'],
            ['warning', 'Warning', '警告'],
            ['info', 'Info', '信息'],
            ['debug', 'Debug', '调试'],
            ['all', 'All', '全部'],
            ['none', 'None', '无'],
        ],
    }),
    field({
        id: 'copilot.screenReader',
        driver: 'copilot',
        group: 'ui',
        path: 'screenReader',
        control: 'toggle',
        label: ['Screen reader', '屏幕阅读器'],
        help: ['Enables terminal output optimized for screen readers.', '启用适合屏幕阅读器的终端输出。'],
        defaultValue: false,
    }),
    field({
        id: 'copilot.updateTerminalTitle',
        driver: 'copilot',
        group: 'ui',
        path: 'updateTerminalTitle',
        control: 'toggle',
        label: ['Terminal title', '终端标题'],
        help: ['Shows current intent in the terminal title.', '在终端标题显示当前意图。'],
        defaultValue: true,
    }),
]
