export const DEFAULT_VIBY_LISTEN_HOST = '127.0.0.1'
export const DEFAULT_VIBY_LISTEN_PORT = 37173

export const DEFAULT_VIBY_LOCAL_API_URL = `http://localhost:${DEFAULT_VIBY_LISTEN_PORT}`
export const DEFAULT_VIBY_LOCAL_PROXY_URL = `http://${DEFAULT_VIBY_LISTEN_HOST}:${DEFAULT_VIBY_LISTEN_PORT}`
