import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
    assertArchivesExist,
    DEFAULT_TARGETS,
    getFeatureFlag,
    parseTarget,
    resolveTarget,
} from './buildExecutableTarget'

const BUILD_RETRY_ATTEMPTS = 3
const BUILD_RETRY_DELAY_MS = 5_000

function getArg(args: string[], name: string): string | undefined {
    const idx = args.indexOf(name)
    if (idx === -1 || idx + 1 >= args.length) {
        return undefined
    }
    return args[idx + 1]
}

function resolveEntry(projectRoot: string, entry: string | undefined): string {
    return join(projectRoot, entry ?? 'src/appCoreBootstrap.ts')
}

function resolveOutdir(projectRoot: string, outdir: string): string {
    if (isAbsolute(outdir)) {
        return outdir
    }
    return join(projectRoot, outdir)
}

function writeStubEmbeddedAssets(workspaceRoot: string): void {
    const outputPath = join(workspaceRoot, 'hub', 'src', 'web', 'embeddedAssets.generated.ts')
    const contents = [
        '// This file is generated by app-core/scripts/build-executable.ts when --with-web-assets is not used.',
        '// It intentionally contains no embedded assets.',
        '',
        'export interface EmbeddedWebAsset {',
        '    path: string;',
        '    sourcePath: string;',
        '    mimeType: string;',
        '}',
        '',
        'export const embeddedAssets: EmbeddedWebAsset[] = [];',
        '',
    ].join('\n')
    writeFileSync(outputPath, contents, 'utf-8')
}

function isStubEmbeddedAssets(manifestPath: string): boolean {
    try {
        const contents = readFileSync(manifestPath, 'utf-8')
        return contents.includes('intentionally contains no embedded assets')
    } catch {
        return false
    }
}

function ensureEmbeddedAssetsManifest(workspaceRoot: string, includeWebAssets: boolean): void {
    const manifestPath = join(workspaceRoot, 'hub', 'src', 'web', 'embeddedAssets.generated.ts')
    if (includeWebAssets) {
        if (!existsSync(manifestPath)) {
            throw new Error(
                'Missing embedded web asset manifest. Run `bun run build:web` and `cd hub && bun run generate:embedded-web-assets`, or `bun run build:app-core` from the repo root.'
            )
        }
        if (isStubEmbeddedAssets(manifestPath)) {
            throw new Error(
                'Embedded web asset manifest is a stub. Run `bun run build:web` and `cd hub && bun run generate:embedded-web-assets`, or `bun run build:app-core` from the repo root.'
            )
        }
        return
    }

    writeStubEmbeddedAssets(workspaceRoot)
}

async function buildTarget(
    projectRoot: string,
    target: string,
    outdir: string,
    name: string,
    entry?: string
): Promise<void> {
    const { platform, arch } = parseTarget(target)
    assertArchivesExist(projectRoot, platform, arch)
    const outputName = platform === 'win32' ? `${name}.exe` : name
    const outfile = join(outdir, target, outputName)
    mkdirSync(dirname(outfile), { recursive: true })
    const featureFlag = getFeatureFlag(platform, arch)

    const cmd = [
        process.execPath,
        'build',
        '--compile',
        '--no-compile-autoload-dotenv',
        `--feature=${featureFlag}`,
        `--target=${target}`,
        `--outfile=${outfile}`,
        resolveEntry(projectRoot, entry),
    ]

    console.log(`[build:exe] ${cmd.join(' ')}`)

    const proc = Bun.spawn({
        cmd,
        env: process.env,
        stdout: 'inherit',
        stderr: 'inherit',
        cwd: projectRoot,
    })

    const exitCode = await proc.exited
    if (exitCode !== 0) {
        throw new Error(`Build failed for target ${target} (exit ${exitCode})`)
    }
}

async function buildTargetWithRetry(
    projectRoot: string,
    target: string,
    outdir: string,
    name: string,
    entry?: string
): Promise<void> {
    let lastError: unknown

    for (let attempt = 1; attempt <= BUILD_RETRY_ATTEMPTS; attempt += 1) {
        try {
            await buildTarget(projectRoot, target, outdir, name, entry)
            return
        } catch (error) {
            lastError = error
            if (attempt === BUILD_RETRY_ATTEMPTS) {
                break
            }

            console.warn(
                `[build:exe] Attempt ${attempt}/${BUILD_RETRY_ATTEMPTS} failed for ${target}; retrying in ${BUILD_RETRY_DELAY_MS / 1000}s`
            )
            console.warn(`[build:exe] ${error instanceof Error ? error.message : String(error)}`)
            await Bun.sleep(BUILD_RETRY_DELAY_MS)
        }
    }

    throw lastError instanceof Error ? lastError : new Error(String(lastError))
}

async function main(): Promise<void> {
    const args = process.argv.slice(2)
    const target = getArg(args, '--target')
    const outdirArg = getArg(args, '--outdir') ?? 'dist-exe'
    const name = getArg(args, '--name') ?? 'viby-app-core'
    const buildAll = args.includes('--all')
    const includeWebAssets = args.includes('--with-web-assets')
    const entry = getArg(args, '--entry') ?? 'src/appCoreBootstrap.ts'

    if (args.includes('--target') && !target) {
        console.error(
            'Usage: bun run scripts/build-executable.ts [--target <bun-platform[-arch[-variant]]>] [--outdir dist-exe] [--name viby-app-core] [--entry src/appCoreBootstrap.ts] [--with-web-assets]'
        )
        console.error(
            '   or: bun run scripts/build-executable.ts --all [--outdir dist-exe] [--name viby-app-core] [--entry src/appCoreBootstrap.ts] [--with-web-assets]'
        )
        process.exit(1)
    }

    if (!buildAll && !target) {
        console.log('[build:exe] No --target provided; defaulting to host platform + arch.')
    }

    const scriptDir = dirname(fileURLToPath(import.meta.url))
    const projectRoot = join(scriptDir, '..')
    const workspaceRoot = join(projectRoot, '..')
    const outdir = resolveOutdir(projectRoot, outdirArg)
    const resolvedTarget = buildAll ? undefined : resolveTarget(target)
    const targets = buildAll ? DEFAULT_TARGETS : [resolvedTarget!]

    ensureEmbeddedAssetsManifest(workspaceRoot, includeWebAssets)

    for (const targetName of targets) {
        await buildTargetWithRetry(projectRoot, targetName, outdir, name, entry)
    }
}

main().catch((error) => {
    console.error(`[build:exe] ${error instanceof Error ? error.message : String(error)}`)
    process.exit(1)
})
