export const PAIRING_SESSION_TTL_SECONDS = 30 * 24 * 60 * 60
export const PAIRING_TICKET_TTL_SECONDS = 10 * 60
export const PAIRING_RECONNECT_CHALLENGE_TTL_SECONDS = 60
export const PAIRING_TURN_CREDENTIAL_TTL_SECONDS = 10 * 60

export const PAIRING_MOBILE_DISCONNECT_GRACE_SECONDS = 10 * 60
export const PAIRING_MOBILE_DISCONNECT_GRACE_MS = PAIRING_MOBILE_DISCONNECT_GRACE_SECONDS * 1000

export const PAIRING_CONNECT_TIMEOUT_MS = 30_000
export const PAIRING_PEER_REQUEST_TIMEOUT_MS = 30_000
export const PAIRING_SIGNAL_RECONNECT_DELAY_MS = 1_000
export const PAIRING_SIGNAL_PING_INTERVAL_MS = 20_000
export const PAIRING_SIGNAL_FOREGROUND_JOIN_ACK_TIMEOUT_MS = 1_500
export const PAIRING_ICE_RESTART_MIN_INTERVAL_MS = 10_000
export const PAIRING_STATS_POLL_INTERVAL_MS = 10_000
export const PAIRING_TELEMETRY_REPORT_INTERVAL_MS = 60_000

export const PAIRING_REMOTE_RECONNECT_BASE_DELAY_MS = 750
export const PAIRING_REMOTE_RECONNECT_MAX_DELAY_MS = 10_000
